/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import enums.MorfologiaEnum;
import javax.swing.JRadioButton;

/**
 *
 * @author Peu
 */
public class PanelMenuMorfologia extends javax.swing.JPanel {

    private static PanelMenuMorfologia instance;
    private MorfologiaEnum tipoAlgoritmo;
    /**
     * Creates new form PanelFiltros
     */
    public PanelMenuMorfologia() {
        initComponents();
    }
    
    public static synchronized PanelMenuMorfologia getInstance() {
        if (instance == null) {
            instance = new PanelMenuMorfologia();
        }
        return instance;
    }
    
    public int getDados() {
        return (int) js_dados.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gBtn_operacoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_dilatacao = new javax.swing.JRadioButton();
        rb_erosao = new javax.swing.JRadioButton();
        rb_gradiente = new javax.swing.JRadioButton();
        rb_abertura = new javax.swing.JRadioButton();
        rb_fechamento = new javax.swing.JRadioButton();
        rb_topHat = new javax.swing.JRadioButton();
        rb_bottomHat = new javax.swing.JRadioButton();
        panelDados = new javax.swing.JPanel();
        lab_dados = new javax.swing.JLabel();
        js_dados = new javax.swing.JSpinner();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operação"));

        gBtn_operacoes.add(rb_dilatacao);
        rb_dilatacao.setText("Dilatação");
        rb_dilatacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarOperacao(evt);
            }
        });

        gBtn_operacoes.add(rb_erosao);
        rb_erosao.setText("Erosão");

        gBtn_operacoes.add(rb_gradiente);
        rb_gradiente.setText("Gradiente morfológico");

        gBtn_operacoes.add(rb_abertura);
        rb_abertura.setText("Abertura");

        gBtn_operacoes.add(rb_fechamento);
        rb_fechamento.setText("Fechamento");

        gBtn_operacoes.add(rb_topHat);
        rb_topHat.setText("Top-Hat");

        gBtn_operacoes.add(rb_bottomHat);
        rb_bottomHat.setText("Bottom-Hat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_dilatacao)
                    .addComponent(rb_erosao)
                    .addComponent(rb_gradiente)
                    .addComponent(rb_abertura)
                    .addComponent(rb_fechamento)
                    .addComponent(rb_topHat)
                    .addComponent(rb_bottomHat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_dilatacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_erosao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_gradiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_abertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_fechamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_topHat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_bottomHat))
        );

        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        lab_dados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_dados.setText("Numero de vezes a ser aplicado");

        js_dados.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_dados, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addComponent(js_dados)
                .addContainerGap())
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_dados)
                .addGap(18, 18, 18)
                .addComponent(js_dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarOperacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarOperacao
        JRadioButton radio = (JRadioButton) evt.getSource();
        PanelMorfologia.getInstance().setTitle("Operação de " + radio.getText());

        if (rb_gradiente.isSelected()) {
            panelDados.setVisible(false);
        } else {
            panelDados.setVisible(true);
        }
    }//GEN-LAST:event_selecionarOperacao


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gBtn_operacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner js_dados;
    private javax.swing.JLabel lab_dados;
    private javax.swing.JPanel panelDados;
    private javax.swing.JRadioButton rb_abertura;
    private javax.swing.JRadioButton rb_bottomHat;
    private javax.swing.JRadioButton rb_dilatacao;
    private javax.swing.JRadioButton rb_erosao;
    private javax.swing.JRadioButton rb_fechamento;
    private javax.swing.JRadioButton rb_gradiente;
    private javax.swing.JRadioButton rb_topHat;
    // End of variables declaration//GEN-END:variables
    
    public MorfologiaEnum getTipoAlgoritimo() {
        if (rb_dilatacao.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.DILATACAO);
        } else if (rb_erosao.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.EROSAO);
        } else if (rb_gradiente.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.GRADIENTEMORFOLOGICO);
        } else if (rb_abertura.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.ABERTURA);
        } else if (rb_fechamento.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.FECHAMENTO);
        } else if (rb_topHat.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.TOPHAT);
        } else if (rb_bottomHat.isSelected()) {
            setTipoAlgoritimo(MorfologiaEnum.BOTTOMHAT);
        }

        return tipoAlgoritmo;
    }
    
    public void setTipoAlgoritimo(MorfologiaEnum tipoAlgoritimo) {
        this.tipoAlgoritmo = tipoAlgoritimo;
    }
    
}
