/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import enums.FiltrosEnum;
import javax.swing.JRadioButton;

/**
 *
 * @author Peu
 */
public class PanelMenuFiltros extends javax.swing.JPanel {
    
    private static PanelMenuFiltros instance;
    private FiltrosEnum tipoAlgoritmo;
    /**
     * Creates new form PanelFiltros
     */
    public PanelMenuFiltros() {
        initComponents();
    }
    
    public static synchronized PanelMenuFiltros getInstance() {
        if (instance == null) {
            instance = new PanelMenuFiltros();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rb_media = new javax.swing.JRadioButton();
        rb_mediana = new javax.swing.JRadioButton();
        rb_passaAltaB = new javax.swing.JRadioButton();
        rb_roberts = new javax.swing.JRadioButton();
        rb_robertsC = new javax.swing.JRadioButton();
        rb_prewitt = new javax.swing.JRadioButton();
        rb_altoReforco = new javax.swing.JRadioButton();
        rb_sobel = new javax.swing.JRadioButton();
        panelDados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        js_a = new javax.swing.JSpinner();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        rb_media.setText("Média");
        rb_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mediaActionPerformed(evt);
            }
        });

        rb_mediana.setText("Mediana");

        rb_passaAltaB.setText("Passa Alta Básico");

        rb_roberts.setText("Operador de Robert's");

        rb_robertsC.setText("Operador de Robert's Cruzado");

        rb_prewitt.setText("Operador de Prewitt");

        rb_altoReforco.setText("Alto Reforço (High Boost)");

        rb_sobel.setText("Operador de Sobel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_media)
                    .addComponent(rb_mediana)
                    .addComponent(rb_passaAltaB)
                    .addComponent(rb_roberts)
                    .addComponent(rb_robertsC)
                    .addComponent(rb_prewitt)
                    .addComponent(rb_altoReforco)
                    .addComponent(rb_sobel))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_media)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_mediana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_passaAltaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_roberts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_robertsC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_prewitt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_altoReforco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_sobel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel1.setText("Valor de A");

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_a, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(js_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 324, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rb_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mediaActionPerformed
        JRadioButton radio = (JRadioButton) evt.getSource();
        PanelFiltros.getInstance().setTitle("Filtro de " + radio.getText());

        if (rb_altoReforco.isSelected()) {
            panelDados.setVisible(true);
        } else {
            panelDados.setVisible(false);
        }
    }//GEN-LAST:event_rb_mediaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner js_a;
    private javax.swing.JPanel panelDados;
    private javax.swing.JRadioButton rb_altoReforco;
    private javax.swing.JRadioButton rb_media;
    private javax.swing.JRadioButton rb_mediana;
    private javax.swing.JRadioButton rb_passaAltaB;
    private javax.swing.JRadioButton rb_prewitt;
    private javax.swing.JRadioButton rb_roberts;
    private javax.swing.JRadioButton rb_robertsC;
    private javax.swing.JRadioButton rb_sobel;
    // End of variables declaration//GEN-END:variables
    
    public FiltrosEnum getTipoAlgoritimo() {
        if (rb_media.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.MEDIA);
        } else if (rb_mediana.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.MEDIANA);
        } else if (rb_altoReforco.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.ALTO_REFORCO);
        } else if (rb_passaAltaB.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.PASSA_ALTA_BASICO);
        } else if (rb_prewitt.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.OPERADOR_PEWITT);
        } else if (rb_roberts.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.OPERADOR_ROBERTS);
        } else if (rb_sobel.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.OPERADOR_SOBEL);
        } else if (rb_robertsC.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.OPERADOR_ROBERTS_CRUZADO);
        }

        return tipoAlgoritmo;
    }

    public void setTipoAlgoritimo(FiltrosEnum tipoAlgoritimo) {
        this.tipoAlgoritmo = tipoAlgoritimo;
    }
    
    public double getA() {
        return ((Integer) js_a.getValue()).doubleValue();
    }
    
}
