/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import enums.MorfologiaBinEnum;
import javax.swing.JRadioButton;

/**
 *
 * @author Peu
 */
public class PanelMenuMorfologiaBin extends javax.swing.JPanel {

    private static PanelMenuMorfologiaBin instance;
    private MorfologiaBinEnum tipoAlgoritmo;
    /**
     * Creates new form PanelFiltros
     */
    public PanelMenuMorfologiaBin() {
        initComponents();
    }
    
    public static synchronized PanelMenuMorfologiaBin getInstance() {
        if (instance == null) {
            instance = new PanelMenuMorfologiaBin();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_dilatacao = new javax.swing.JRadioButton();
        rb_erosao = new javax.swing.JRadioButton();
        rb_fechamento = new javax.swing.JRadioButton();
        rb_abertura = new javax.swing.JRadioButton();
        rb_hitOrMiss = new javax.swing.JRadioButton();
        rb_contornoExterno = new javax.swing.JRadioButton();
        rb_contornoInterno = new javax.swing.JRadioButton();
        rb_gradienteMorfologico = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operação"));

        buttonGroup1.add(rb_dilatacao);
        rb_dilatacao.setText("Dilatação");

        buttonGroup1.add(rb_erosao);
        rb_erosao.setText("Erosão");

        buttonGroup1.add(rb_fechamento);
        rb_fechamento.setText("Fechamento");

        buttonGroup1.add(rb_abertura);
        rb_abertura.setText("Abertura");

        buttonGroup1.add(rb_hitOrMiss);
        rb_hitOrMiss.setText("Hit-or-Miss");

        buttonGroup1.add(rb_contornoExterno);
        rb_contornoExterno.setText("Contorno externo");

        buttonGroup1.add(rb_contornoInterno);
        rb_contornoInterno.setText("Contorno interno");

        buttonGroup1.add(rb_gradienteMorfologico);
        rb_gradienteMorfologico.setText("Gradiente morfológico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_dilatacao)
                    .addComponent(rb_erosao)
                    .addComponent(rb_fechamento)
                    .addComponent(rb_abertura)
                    .addComponent(rb_hitOrMiss)
                    .addComponent(rb_contornoExterno)
                    .addComponent(rb_contornoInterno)
                    .addComponent(rb_gradienteMorfologico))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_dilatacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_erosao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_fechamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_abertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_hitOrMiss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_contornoExterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_contornoInterno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_gradienteMorfologico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_abertura;
    private javax.swing.JRadioButton rb_contornoExterno;
    private javax.swing.JRadioButton rb_contornoInterno;
    private javax.swing.JRadioButton rb_dilatacao;
    private javax.swing.JRadioButton rb_erosao;
    private javax.swing.JRadioButton rb_fechamento;
    private javax.swing.JRadioButton rb_gradienteMorfologico;
    private javax.swing.JRadioButton rb_hitOrMiss;
    // End of variables declaration//GEN-END:variables
    
    public MorfologiaBinEnum getTipoAlgoritimo() {
        if (rb_dilatacao.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.DILATACAO);
        } else if (rb_erosao.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.EROSAO);
        } else if (rb_gradienteMorfologico.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.GRADIENTEMORFOLOGICO);
        } else if (rb_abertura.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.ABERTURA);
        } else if (rb_fechamento.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.FECHAMENTO);
        } else if (rb_contornoExterno.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.CONTORNOEXTERNO);
        } else if (rb_contornoInterno.isSelected()) {
            setTipoAlgoritimo(MorfologiaBinEnum.CONTORNOINTERNO);
        } else if(rb_hitOrMiss.isSelected()){
            setTipoAlgoritimo(MorfologiaBinEnum.HITORMISS);
        }

        return tipoAlgoritmo;
    }
    
    public void setTipoAlgoritimo(MorfologiaBinEnum tipoAlgoritimo) {
        this.tipoAlgoritmo = tipoAlgoritimo;
    }
    
}
