/*
 * Painel das operações entre duas imagens.
 */
package panels;

import enums.OperacoesEnum;
import javax.swing.JRadioButton;

public class PanelMenuOperacoes extends javax.swing.JPanel {

    private static PanelMenuOperacoes instance;
    private OperacoesEnum tipoAlgoritimo;

    public static synchronized PanelMenuOperacoes getInstance() {
        if (instance == null) {
            instance = new PanelMenuOperacoes();
        }
        return instance;
    }

    private PanelMenuOperacoes() {
        initComponents();
    }

    public OperacoesEnum getTipoAlgoritimo() {
        if (rb_adicao.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.ADICAO;
        } else if (rb_subtracao.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.SUBSTRACAO;
        } else if (rb_multiplicacao.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.MULTIPLICACAO;
        } else if (rb_divisao.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.DIVISAO;
        } else if (rb_AND.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.AND;
        } else if (rb_OR.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.OR;
        } else if (rb_XOR.isSelected()) {
            tipoAlgoritimo = OperacoesEnum.XOR;
        }
        
        return tipoAlgoritimo;
    }

    public void setTipoAlgoritimo(OperacoesEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gBtn_opr = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_adicao = new javax.swing.JRadioButton();
        rb_subtracao = new javax.swing.JRadioButton();
        rb_multiplicacao = new javax.swing.JRadioButton();
        rb_divisao = new javax.swing.JRadioButton();
        rb_OR = new javax.swing.JRadioButton();
        rb_AND = new javax.swing.JRadioButton();
        rb_XOR = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        gBtn_opr.add(rb_adicao);
        rb_adicao.setText("Adição");

        gBtn_opr.add(rb_subtracao);
        rb_subtracao.setText("Subtração");

        gBtn_opr.add(rb_multiplicacao);
        rb_multiplicacao.setText("Multiplicação");

        gBtn_opr.add(rb_divisao);
        rb_divisao.setText("Dvisão");

        gBtn_opr.add(rb_OR);
        rb_OR.setText("OR");

        gBtn_opr.add(rb_AND);
        rb_AND.setText("AND");
        rb_AND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarFiltro(evt);
            }
        });

        gBtn_opr.add(rb_XOR);
        rb_XOR.setText("XOR");
        rb_XOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarFiltro(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_adicao)
                    .addComponent(rb_subtracao)
                    .addComponent(rb_multiplicacao)
                    .addComponent(rb_divisao)
                    .addComponent(rb_OR)
                    .addComponent(rb_AND)
                    .addComponent(rb_XOR))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_adicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_subtracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_multiplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_divisao)
                .addGap(18, 18, 18)
                .addComponent(rb_OR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_AND)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_XOR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelecionarFiltro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarFiltro
        JRadioButton radio = (JRadioButton) evt.getSource();
        PanelOperacoes.getInstance().setTitle("Operação de " + radio.getText());
        //PanelOperacoes.panel_resultado.repaint();
    }//GEN-LAST:event_SelecionarFiltro


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gBtn_opr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_AND;
    private javax.swing.JRadioButton rb_OR;
    private javax.swing.JRadioButton rb_XOR;
    private javax.swing.JRadioButton rb_adicao;
    private javax.swing.JRadioButton rb_divisao;
    private javax.swing.JRadioButton rb_multiplicacao;
    private javax.swing.JRadioButton rb_subtracao;
    // End of variables declaration//GEN-END:variables
}
