/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import auxiliar.Ponto;
import enums.TransformEnum;
import java.awt.Color;
import java.awt.geom.Rectangle2D;
import java.util.Stack;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import operacoes.PlanoCartesiano;
import view.JanelaPrincipal;

/**
 *
 * @author Peu
 */
public class PanelMenu2D extends javax.swing.JPanel {
    
    private static PanelMenu2D instance;
    public static double[][] matrizObject;
    public Stack<double[][]> listaDeTransformacoes;

    private Rectangle2D.Double rect;
    private double valorX, valorY; // usando na translacao, escala, cisalhamento
    private Ponto ponto;
    private double angulo; // usado na  rotacao
    private String eixo; // usado na reflexao

    private Color color;
    private TransformEnum tipoAlgoritimo;
    private final DefaultListModel<String> modelList;

    public static synchronized PanelMenu2D getInstance() {
        if (instance == null) {
            instance = new PanelMenu2D();
        }
        return instance;
    }
    
    /**
     * Creates new form PanelMenu2D
     */
    public PanelMenu2D() {
        modelList = new DefaultListModel();
        listaDeTransformacoes = new Stack<>();
        initComponents();
        pan_dados1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sp_width = new javax.swing.JSpinner();
        sp_pointX = new javax.swing.JSpinner();
        sp_height = new javax.swing.JSpinner();
        sp_pointY = new javax.swing.JSpinner();
        btn_criarObj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rb_translac = new javax.swing.JRadioButton();
        rb_escal = new javax.swing.JRadioButton();
        rb_rot = new javax.swing.JRadioButton();
        rb_reflex = new javax.swing.JRadioButton();
        rb_cisa = new javax.swing.JRadioButton();
        pan_dados1 = new javax.swing.JPanel();
        lb_dd1 = new javax.swing.JLabel();
        lb_dd2 = new javax.swing.JLabel();
        valorDDX = new javax.swing.JSpinner();
        valorDDY = new javax.swing.JSpinner();
        pan_dados2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btn_applyTransf = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Objeto 2D"));

        jLabel1.setText("W");

        jLabel2.setText("X");

        jLabel3.setText("H");

        jLabel4.setText("Y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_width, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_pointX, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_pointY)
                    .addComponent(sp_height, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(sp_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(sp_pointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_pointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_criarObj.setText("Criar Objeto");
        btn_criarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarObjActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transformações"));

        buttonGroup1.add(rb_translac);
        rb_translac.setText("Translação");
        rb_translac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_escal);
        rb_escal.setText("Escala");
        rb_escal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_rot);
        rb_rot.setText("Rotação");
        rb_rot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_reflex);
        rb_reflex.setText("Reflexão");
        rb_reflex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_cisa);
        rb_cisa.setText("Cisalhamento");
        rb_cisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_translac)
                    .addComponent(rb_escal)
                    .addComponent(rb_rot)
                    .addComponent(rb_reflex)
                    .addComponent(rb_cisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_translac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_escal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_rot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_reflex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_cisa))
        );

        pan_dados1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        lb_dd1.setText("X");

        lb_dd2.setText("Y");

        javax.swing.GroupLayout pan_dados1Layout = new javax.swing.GroupLayout(pan_dados1);
        pan_dados1.setLayout(pan_dados1Layout);
        pan_dados1Layout.setHorizontalGroup(
            pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dd1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_dd2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorDDY, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorDDX, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_dados1Layout.setVerticalGroup(
            pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dd1)
                    .addComponent(valorDDX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dd2)
                    .addComponent(valorDDY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_dados2.setBorder(javax.swing.BorderFactory.createTitledBorder("Eixo"));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Reflexão em X");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Reflexão em Y");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Reflexão em X e Y");

        javax.swing.GroupLayout pan_dados2Layout = new javax.swing.GroupLayout(pan_dados2);
        pan_dados2.setLayout(pan_dados2Layout);
        pan_dados2Layout.setHorizontalGroup(
            pan_dados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_dados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_dados2Layout.setVerticalGroup(
            pan_dados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_applyTransf.setText("Aplicar Transformação");
        btn_applyTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_applyTransfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_applyTransf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_dados2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_dados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_criarObj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_criarObj, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_dados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_dados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_applyTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_applyTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyTransfActionPerformed
        if(rb_translac.isSelected()){
            setTipoAlgoritimo(TransformEnum.TRANSLACAO);
            setValorX((double) valorDDX.getValue());
            setValorY((double) valorDDY.getValue());
        } else if(rb_escal.isSelected()){
            setTipoAlgoritimo(TransformEnum.ESCALA);
            setValorX((double) valorDDX.getValue());
            setValorY((double) valorDDY.getValue());
        } else if(rb_rot.isSelected()){
            setTipoAlgoritimo(TransformEnum.ROTACAO);
            setAngulo((double) valorDDX.getValue());
        } else if(rb_reflex.isSelected()){
            setTipoAlgoritimo(TransformEnum.REFLEXAO);
            if (jRadioButton1.isSelected()) {
                setEixo("x");
            } else if (jRadioButton2.isSelected()) {
                setEixo("y");
            } else if (jRadioButton3.isSelected()) {
                setEixo("xy");
            }
        } else if(rb_cisa.isSelected()){
            setTipoAlgoritimo(TransformEnum.CISALHAMENTO);
            setValorX((double) valorDDX.getValue());
            setValorY((double) valorDDY.getValue());
        }
        
        if (matrizObject == null) {
            JOptionPane.showMessageDialog(this.getRootPane(), "Não há objeto no plano cartesiano!\nPor favor, desenhe o objeto primeiro...", "Aplicar Transformação?", JOptionPane.WARNING_MESSAGE);
        } else {
            JanelaPrincipal.runResult(this);
        }
    }//GEN-LAST:event_btn_applyTransfActionPerformed

    private void transformacaoSelecionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformacaoSelecionada
        pan_dados1.setVisible(true);
        pan_dados2.setVisible(false);

        valorDDX.setValue(0D);
        valorDDY.setValue(0D);

        if (rb_rot.isSelected()) {
            lb_dd1.setText("Ângulo");
            lb_dd2.setVisible(false);
            valorDDY.setVisible(false);
        } else if (rb_reflex.isSelected()) {
            pan_dados1.setVisible(false);
            pan_dados2.setVisible(true);
        } else {
            lb_dd1.setText("X");
            lb_dd2.setVisible(true);
            valorDDY.setVisible(true);
        }
    }//GEN-LAST:event_transformacaoSelecionada

    private void btn_criarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarObjActionPerformed
        desenharObjeto();
    }//GEN-LAST:event_btn_criarObjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_applyTransf;
    private javax.swing.JButton btn_criarObj;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel lb_dd1;
    private javax.swing.JLabel lb_dd2;
    private javax.swing.JPanel pan_dados1;
    private javax.swing.JPanel pan_dados2;
    private javax.swing.JRadioButton rb_cisa;
    private javax.swing.JRadioButton rb_escal;
    private javax.swing.JRadioButton rb_reflex;
    private javax.swing.JRadioButton rb_rot;
    private javax.swing.JRadioButton rb_translac;
    private javax.swing.JSpinner sp_height;
    private javax.swing.JSpinner sp_pointX;
    private javax.swing.JSpinner sp_pointY;
    private javax.swing.JSpinner sp_width;
    private javax.swing.JSpinner valorDDX;
    private javax.swing.JSpinner valorDDY;
    // End of variables declaration//GEN-END:variables
    
    public Ponto getPonto() {
        return ponto;
    }

    public void setPonto(Ponto ponto) {
        this.ponto = ponto;
    }

    public double getValorX() {
        return valorX;
    }

    public void setValorX(double valorX) {
        this.valorX = valorX;
    }

    public double getValorY() {
        return valorY;
    }

    public void setValorY(double valorY) {
        this.valorY = valorY;
    }

    public double getAngulo() {
        return angulo;
    }

    public void setAngulo(double raio) {
        this.angulo = raio;
    }

    public Rectangle2D.Double getRect() {
        return rect;
    }

    public void setRect(Rectangle2D.Double rect) {
        this.rect = rect;
    }

    public String getEixo() {
        return eixo;
    }

    public void setEixo(String eixo) {
        this.eixo = eixo;
    }
    
    public TransformEnum getTipoAlgoritimo() {
        return tipoAlgoritimo;
    }

    public void setTipoAlgoritimo(TransformEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }
    
    private void desenharObjeto() {

        double width = (double) sp_width.getValue();
        double height = (double) sp_height.getValue();

        /**
         * Pegando as coordenadas iniciais do objeto
         */
        double px = (double) sp_pointX.getValue();
        double py = (double) sp_pointY.getValue();

        if (width > 0 && height > 0) {

            matrizObject = new double[3][4];

            // PONTO A
            matrizObject[0][0] = px;
            matrizObject[1][0] = py;
            matrizObject[2][0] = 1;

            // PONTO B
            matrizObject[0][1] = width + px;
            matrizObject[1][1] = 0 + py;
            matrizObject[2][1] = 1;

            // PONTO C
            matrizObject[0][2] = width + px;
            matrizObject[1][2] = height + py;
            matrizObject[2][2] = 1;

            // PONTO D
            matrizObject[0][3] = 0 + px;
            matrizObject[1][3] = height + py;
            matrizObject[2][3] = 1;

            PlanoCartesiano.getInstance().drawObjeto2D(matrizObject);
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "Faltou você definir a largura (W) e altura (H) do objeto!", "Desenhar Objeto?", JOptionPane.WARNING_MESSAGE);
        }
    }
    
}
