/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import auxiliar.Ponto;
import enums.TransformEnum;
import graficos.PanelGrafico;
import java.awt.Color;
import java.util.Stack;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import operacaoMatrizes.Matriz;
import operacoes.PlanoCartesiano;
import view.JanelaPrincipal;

/**
 *
 * @author Peu
 */
public class PanelMenu3D extends javax.swing.JPanel {
    
    private final DefaultListModel<String> modelList;
    private TransformEnum tipoAlgoritimo;
    private static PanelMenu3D instance;
    public static double[][] matrizObjeto3D;
    public Stack<double[][]> listaTransformacoes;
    private double valorX, valorY, valorZ; // usando na translacao, escala, cisalhamento
    private Ponto ponto;
    private double angulo; // usado na  rotacao
    private String eixo; // usado na reflexao
    public static synchronized PanelMenu3D getInstance() {
        if (instance == null) {
            instance = new PanelMenu3D();
        }
        return instance;
    }

    
    
    /**
     * Creates new form PanelTransfor3d
     */
    public PanelMenu3D() {
        modelList = new DefaultListModel();
        listaTransformacoes = new Stack<>();

        initComponents();
        
        pan_eixo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btG_transformacoes = new javax.swing.ButtonGroup();
        btG_eixo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        js_width = new javax.swing.JSpinner();
        js_height = new javax.swing.JSpinner();
        js_depth = new javax.swing.JSpinner();
        btn_CriarObj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rb_translacao = new javax.swing.JRadioButton();
        rb_escala = new javax.swing.JRadioButton();
        rb_rotacao = new javax.swing.JRadioButton();
        rb_reflexao = new javax.swing.JRadioButton();
        rb_cisalhamento = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        js_DDx = new javax.swing.JSpinner();
        js_DDy = new javax.swing.JSpinner();
        js_DDz = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        pan_eixo = new javax.swing.JPanel();
        rb_refXY = new javax.swing.JRadioButton();
        rb_refYZ = new javax.swing.JRadioButton();
        rb_refXZ = new javax.swing.JRadioButton();
        btn_AplicarT = new javax.swing.JButton();
        btn_addListaT = new javax.swing.JButton();
        btn_AplicarTC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaT = new javax.swing.JList<>();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar objeto 3D"));

        jLabel1.setText("W");

        jLabel2.setText("H");

        jLabel3.setText("D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_width, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_height, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_depth)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(js_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(js_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(js_depth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_CriarObj.setText("Criar objeto");
        btn_CriarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarObjActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transformações"));

        btG_transformacoes.add(rb_translacao);
        rb_translacao.setText("Translação");

        btG_transformacoes.add(rb_escala);
        rb_escala.setText("Escala");

        btG_transformacoes.add(rb_rotacao);
        rb_rotacao.setText("Rotação");

        btG_transformacoes.add(rb_reflexao);
        rb_reflexao.setText("Reflexão");

        btG_transformacoes.add(rb_cisalhamento);
        rb_cisalhamento.setText("Cisalhamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_translacao)
                    .addComponent(rb_escala)
                    .addComponent(rb_rotacao)
                    .addComponent(rb_reflexao)
                    .addComponent(rb_cisalhamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_translacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_escala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_rotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_reflexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_cisalhamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel4.setText("      X                      Y                    Z");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(js_DDx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(js_DDy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(js_DDz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_DDx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_DDz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_DDy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pan_eixo.setBorder(javax.swing.BorderFactory.createTitledBorder("Eixo"));

        btG_eixo.add(rb_refXY);
        rb_refXY.setText("Reflexão em XY");

        btG_eixo.add(rb_refYZ);
        rb_refYZ.setText("Reflexão em YZ");

        btG_eixo.add(rb_refXZ);
        rb_refXZ.setText("Reflexão em XZ");

        javax.swing.GroupLayout pan_eixoLayout = new javax.swing.GroupLayout(pan_eixo);
        pan_eixo.setLayout(pan_eixoLayout);
        pan_eixoLayout.setHorizontalGroup(
            pan_eixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_eixoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_eixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_refXY)
                    .addComponent(rb_refYZ)
                    .addComponent(rb_refXZ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_eixoLayout.setVerticalGroup(
            pan_eixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_eixoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_refXY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_refYZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_refXZ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_AplicarT.setText("Aplicar transformação");
        btn_AplicarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AplicarTActionPerformed(evt);
            }
        });

        btn_addListaT.setText("Adicionar a lista de trans. composta");
        btn_addListaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addListaTActionPerformed(evt);
            }
        });

        btn_AplicarTC.setText("Aplicar transformações compostas");
        btn_AplicarTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AplicarTCActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Transformações Compostas"));

        jScrollPane1.setViewportView(jl_listaT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_AplicarTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addListaT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_AplicarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_eixo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CriarObj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CriarObj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_eixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AplicarT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addListaT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_AplicarTC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addListaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addListaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addListaTActionPerformed

    private void btn_CriarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarObjActionPerformed
        desenharObjeto();
    }//GEN-LAST:event_btn_CriarObjActionPerformed

    private void btn_AplicarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AplicarTActionPerformed
        /**
         * Seta o tipo de algoritmo selecionado e seus parametros necessários
         */
        if (rb_translacao.isSelected()) {
            setTipoAlgoritimo(TransformEnum.TRANSLACAO);
            setValorX(((Integer) js_DDx.getValue()).doubleValue());
            setValorY(((Integer) js_DDy.getValue()).doubleValue());
            setValorZ(((Integer) js_DDz.getValue()).doubleValue());
        } else if (rb_escala.isSelected()) {
            setTipoAlgoritimo(TransformEnum.ESCALA);
            setValorX(((Integer) js_DDx.getValue()).doubleValue());
            setValorY(((Integer) js_DDy.getValue()).doubleValue());
            setValorZ(((Integer) js_DDz.getValue()).doubleValue());
        } else if (rb_rotacao.isSelected()) {
            setTipoAlgoritimo(TransformEnum.ROTACAO);
            setAngulo(((Integer) js_DDx.getValue()).doubleValue());

            if (rb_refXY.isSelected()) {
                setEixo("x");
            } else if (rb_refYZ.isSelected()) {
                setEixo("y");
            } else if (rb_refXZ.isSelected()) {
                setEixo("z");
            }
        } else if (rb_reflexao.isSelected()) {
            setTipoAlgoritimo(TransformEnum.REFLEXAO);
            if (rb_refXY.isSelected()) {
                setEixo("xy");
            } else if (rb_refYZ.isSelected()) {
                setEixo("yz");
            } else if (rb_refXZ.isSelected()) {
                setEixo("xz");
            }
        } else if (rb_cisalhamento.isSelected()) {
            setTipoAlgoritimo(TransformEnum.CISALHAMENTO);
            setValorX(((Integer) js_DDx.getValue()).doubleValue());
            setValorY(((Integer) js_DDy.getValue()).doubleValue());
            setValorZ(((Integer) js_DDz.getValue()).doubleValue());
        }

        if (matrizObjeto3D == null) {
            JOptionPane.showMessageDialog(this.getRootPane(), "Não há objeto no plano cartesiano!\nPor favor, desenhe o objeto primeiro...", "Aplicar Transformação?", JOptionPane.WARNING_MESSAGE);
        } else {
            //verificar
            JanelaPrincipal.runResult(this);
        }
    }//GEN-LAST:event_btn_AplicarTActionPerformed

    private void btn_AplicarTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AplicarTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AplicarTCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btG_eixo;
    private javax.swing.ButtonGroup btG_transformacoes;
    private javax.swing.JButton btn_AplicarT;
    private javax.swing.JButton btn_AplicarTC;
    private javax.swing.JButton btn_CriarObj;
    private javax.swing.JButton btn_addListaT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jl_listaT;
    private javax.swing.JSpinner js_DDx;
    private javax.swing.JSpinner js_DDy;
    private javax.swing.JSpinner js_DDz;
    private javax.swing.JSpinner js_depth;
    private javax.swing.JSpinner js_height;
    private javax.swing.JSpinner js_width;
    private javax.swing.JPanel pan_eixo;
    private javax.swing.JRadioButton rb_cisalhamento;
    private javax.swing.JRadioButton rb_escala;
    private javax.swing.JRadioButton rb_refXY;
    private javax.swing.JRadioButton rb_refXZ;
    private javax.swing.JRadioButton rb_refYZ;
    private javax.swing.JRadioButton rb_reflexao;
    private javax.swing.JRadioButton rb_rotacao;
    private javax.swing.JRadioButton rb_translacao;
    // End of variables declaration//GEN-END:variables
    
    public Ponto getPonto() {
        return ponto;
    }

    public void setPonto(Ponto ponto) {
        this.ponto = ponto;
    }

    public double getValorX() {
        return valorX;
    }

    public void setValorX(double valorX) {
        this.valorX = valorX;
    }

    public double getValorY() {
        return valorY;
    }

    public void setValorY(double valorY) {
        this.valorY = valorY;
    }

    public double getValorZ() {
        return valorZ;
    }

    public void setValorZ(double valorZ) {
        this.valorZ = valorZ;
    }

    public double getAngulo() {
        return angulo;
    }

    public void setAngulo(double raio) {
        this.angulo = raio;
    }

    public String getEixo() {
        return eixo;
    }

    public void setEixo(String eixo) {
        this.eixo = eixo;
    }
    
    public TransformEnum getTipoAlgoritmo(){
        return this.tipoAlgoritimo;
    }
    
    public void setTipoAlgoritimo(TransformEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }
    
    private void desenharObjeto() {
        double width = ((Integer) js_width.getValue()).doubleValue();
        double height = ((Integer) js_height.getValue()).doubleValue();
        double depth = ((Integer) js_depth.getValue()).doubleValue();
        
        if (width > 0 && height > 0) {

            matrizObjeto3D = new double[4][8];

            // PONTO A
            matrizObjeto3D[0][0] = 0;
            matrizObjeto3D[1][0] = 0;
            matrizObjeto3D[2][0] = 0;
            matrizObjeto3D[3][0] = 1;

            // PONTO B
            matrizObjeto3D[0][1] = width;
            matrizObjeto3D[1][1] = 0;
            matrizObjeto3D[2][1] = 0;
            matrizObjeto3D[3][1] = 1;

            // PONTO C
            matrizObjeto3D[0][2] = width;
            matrizObjeto3D[1][2] = height;
            matrizObjeto3D[2][2] = 0;
            matrizObjeto3D[3][2] = 1;

            // PONTO D
            matrizObjeto3D[0][3] = 0;
            matrizObjeto3D[1][3] = height;
            matrizObjeto3D[2][3] = 0;
            matrizObjeto3D[3][3] = 1;

            // PONTO E
            matrizObjeto3D[0][4] = (depth / 2);
            matrizObjeto3D[1][4] = (depth / 2);
            matrizObjeto3D[2][4] = 0;
            matrizObjeto3D[3][4] = 1;

            // PONTO F
            matrizObjeto3D[0][5] = (width + depth / 2);
            matrizObjeto3D[1][5] = (depth / 2);
            matrizObjeto3D[2][5] = 0;
            matrizObjeto3D[3][5] = 1;

            // PONTO G
            matrizObjeto3D[0][6] = (width + depth / 2);
            matrizObjeto3D[1][6] = (height + depth / 2);
            matrizObjeto3D[2][6] = 0;
            matrizObjeto3D[3][6] = 1;

            // PONTO H
            matrizObjeto3D[0][7] = (depth / 2);
            matrizObjeto3D[1][7] = (height + depth / 2);
            matrizObjeto3D[2][7] = 0;
            matrizObjeto3D[3][7] = 1;

            PlanoCartesiano.getInstance().drawObjeto3D(matrizObjeto3D);
            Matriz.printMatriz(matrizObjeto3D, "Matriz original");
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "Faltou você definir a largura (W), altura (H) e profundidade (L) do objeto!", "Desenhar Objeto 3D?", JOptionPane.WARNING_MESSAGE);
        }
    }

}
