/*
 * Painel de menu das operações das transformações 2D.
 */
package panels;

import auxiliar.Ponto;
import enums.TransformEnum;
import java.awt.Color;
import java.awt.geom.Rectangle2D;
import java.util.Stack;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import operacoes.PlanoCartesiano;
import transformacoes.Transformacoes2D;
import view.JanelaPrincipal;

public class SubMenuTransfor2d extends javax.swing.JPanel {
    
    private static SubMenuTransfor2d instance;
    public static double[][] matrizObject;
    public Stack<double[][]> listaDeTransformacoes;

    private Rectangle2D.Double rect;
    private double valorX, valorY; // usando na translacao, escala, cisalhamento
    private Ponto ponto;
    private double angulo; // usado na  rotacao
    private String eixo; // usado na reflexao

    private Color color;
    private TransformEnum tipoAlgoritimo;
    private final DefaultListModel<String> modelList;
    
    public static synchronized SubMenuTransfor2d getInstance() {
        if (instance == null) {
            instance = new SubMenuTransfor2d();
        }
        return instance;
    }
    
    /**
     * Creates new form PanelMenuRaster
     */
    public SubMenuTransfor2d() {
        modelList = new DefaultListModel();
        listaDeTransformacoes = new Stack<>();
        initComponents();
        pan_dados1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btn_desenhar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sp_width = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        sp_pointX = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sp_height = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        sp_pointY = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rb_translacao = new javax.swing.JRadioButton();
        rb_escala = new javax.swing.JRadioButton();
        rb_rotacao = new javax.swing.JRadioButton();
        rb_reflexao = new javax.swing.JRadioButton();
        rb_cisalhamento = new javax.swing.JRadioButton();
        pan_dados1 = new javax.swing.JPanel();
        valorDDX = new javax.swing.JSpinner();
        valorDDY = new javax.swing.JSpinner();
        lab_dd1 = new javax.swing.JLabel();
        lab_dd2 = new javax.swing.JLabel();
        btn_applyTransf = new javax.swing.JButton();
        pan_dados2 = new javax.swing.JPanel();
        rb_refX = new javax.swing.JRadioButton();
        rb_refY = new javax.swing.JRadioButton();
        rb_refXY = new javax.swing.JRadioButton();
        btn_addLista = new javax.swing.JButton();
        btn_applyTransfC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setAutoscrolls(true);

        btn_desenhar.setText("Desenhar");
        btn_desenhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desenharActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Desenhar Objeto 2D"));

        sp_width.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel3.setText("W");

        sp_pointX.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel4.setText("X");

        sp_height.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel5.setText("H");

        sp_pointY.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel6.setText("Y");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sp_pointX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_pointY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sp_width, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_height, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(sp_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_pointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sp_pointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de Transformações"));

        buttonGroup1.add(rb_translacao);
        rb_translacao.setText("Translação");
        rb_translacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_escala);
        rb_escala.setText("Escala");
        rb_escala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_rotacao);
        rb_rotacao.setText("Rotação");
        rb_rotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_reflexao);
        rb_reflexao.setText("Reflexão");
        rb_reflexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        buttonGroup1.add(rb_cisalhamento);
        rb_cisalhamento.setText("Cisalhamento");
        rb_cisalhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformacaoSelecionada(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_translacao)
                    .addComponent(rb_escala)
                    .addComponent(rb_rotacao)
                    .addComponent(rb_reflexao)
                    .addComponent(rb_cisalhamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rb_translacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_escala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_rotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_reflexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_cisalhamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_dados1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        valorDDX.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        valorDDY.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        lab_dd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_dd1.setText("X");

        lab_dd2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_dd2.setText("Y");

        javax.swing.GroupLayout pan_dados1Layout = new javax.swing.GroupLayout(pan_dados1);
        pan_dados1.setLayout(pan_dados1Layout);
        pan_dados1Layout.setHorizontalGroup(
            pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorDDX, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(lab_dd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorDDY, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(lab_dd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        pan_dados1Layout.setVerticalGroup(
            pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados1Layout.createSequentialGroup()
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_dd1)
                    .addComponent(lab_dd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_dados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorDDY)
                    .addComponent(valorDDX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btn_applyTransf.setText("Aplicar Transformação");
        btn_applyTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_applyTransfActionPerformed(evt);
            }
        });

        pan_dados2.setBorder(javax.swing.BorderFactory.createTitledBorder("Eixo"));

        buttonGroup2.add(rb_refX);
        rb_refX.setText("Reflexão em X");

        buttonGroup2.add(rb_refY);
        rb_refY.setText("Reflexão em Y");

        buttonGroup2.add(rb_refXY);
        rb_refXY.setText("Reflexão em X e Y");

        javax.swing.GroupLayout pan_dados2Layout = new javax.swing.GroupLayout(pan_dados2);
        pan_dados2.setLayout(pan_dados2Layout);
        pan_dados2Layout.setHorizontalGroup(
            pan_dados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_dados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_refX)
                    .addComponent(rb_refY)
                    .addComponent(rb_refXY))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_dados2Layout.setVerticalGroup(
            pan_dados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_dados2Layout.createSequentialGroup()
                .addComponent(rb_refX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_refY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_refXY))
        );

        btn_addLista.setText("Adicionar a lista de transformações");
        btn_addLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addListaActionPerformed(evt);
            }
        });

        btn_applyTransfC.setText("Aplicar transformações");
        btn_applyTransfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_applyTransfCActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de transformações"));

        jList1.setModel(modelList);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pan_dados2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_applyTransf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_dados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_applyTransfC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_desenhar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_desenhar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_dados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_dados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_applyTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addLista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_applyTransfC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desenharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desenharActionPerformed
       desenharObjeto();
    }//GEN-LAST:event_btn_desenharActionPerformed

    private void btn_applyTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyTransfActionPerformed
        if(rb_translacao.isSelected()){
            setTipoAlgoritimo(TransformEnum.TRANSLACAO);
            setValorX((double) valorDDX.getValue());
            setValorY((double) valorDDY.getValue());
        } else if(rb_escala.isSelected()){
            setTipoAlgoritimo(TransformEnum.ESCALA);
            setValorX((double) valorDDX.getValue());
            setValorY((double) valorDDY.getValue());
        } else if(rb_rotacao.isSelected()){
            setTipoAlgoritimo(TransformEnum.ROTACAO);
            double t = (double) valorDDX.getValue();
            setAngulo(t);
        } else if(rb_reflexao.isSelected()){
            setTipoAlgoritimo(TransformEnum.REFLEXAO);
            if (rb_refX.isSelected()) {
                setEixo("x");
            } else if (rb_refY.isSelected()) {
                setEixo("y");
            } else if (rb_refXY.isSelected()) {
                setEixo("xy");
            }
        } else if(rb_cisalhamento.isSelected()){
            setTipoAlgoritimo(TransformEnum.CISALHAMENTO);
            setValorX((double) valorDDX.getValue());
            setValorY((double) valorDDY.getValue());
        }
        
        if (matrizObject == null) {
            JOptionPane.showMessageDialog(this.getRootPane(), "Não há objeto no plano cartesiano!\nPor favor, desenhe o objeto primeiro...", "Aplicar Transformação?", JOptionPane.WARNING_MESSAGE);
        } else {
            JanelaPrincipal.runResult(this);
        }
    }//GEN-LAST:event_btn_applyTransfActionPerformed

    private void transformacaoSelecionada(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformacaoSelecionada
        pan_dados1.setVisible(true);
        
        pan_dados2.setVisible(false);

        valorDDX.setValue(0D);
        valorDDY.setValue(0D);

        if (rb_rotacao.isSelected()) {
            lab_dd1.setText("Ângulo");
            lab_dd2.setVisible(false);
            valorDDY.setVisible(false);
        } else if (rb_reflexao.isSelected()) {
            pan_dados1.setVisible(false);
            pan_dados2.setVisible(true);
        } else {
            lab_dd1.setText("X");
            lab_dd2.setVisible(true);
            valorDDY.setVisible(true);
        }
    }//GEN-LAST:event_transformacaoSelecionada

    private void btn_addListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addListaActionPerformed
        Transformacoes2D trans2D = Transformacoes2D.getInstance();
        /**
         * Seta o tipo de algoritmo selecionado e seus parametros necessários
         */
        if (rb_translacao.isSelected()) {
            modelList.addElement("- Translação: Tx=" + valorDDX.getValue() + ", Ty=" + valorDDY.getValue());
            listaDeTransformacoes.push(trans2D.geraMatrizTranslacao((double) valorDDX.getValue(), (double) valorDDY.getValue()));
        } else if (rb_escala.isSelected()) {
            modelList.addElement("- Escala: Sx=" + valorDDX.getValue() + ", Sy=" + valorDDY.getValue());
            listaDeTransformacoes.push(trans2D.geraMatrizEscala((double) valorDDX.getValue(), (double) valorDDY.getValue()));
        } else if (rb_rotacao.isSelected()) {
            modelList.addElement("- Rotação: Θ=" + valorDDX.getValue());
            listaDeTransformacoes.push(trans2D.geraMatrizRotacao((double) valorDDX.getValue()));
        } else if (rb_reflexao.isSelected()) {
            if (rb_refX.isSelected()) {
                modelList.addElement("- Reflexão em X");
                listaDeTransformacoes.push(trans2D.geraMatrizReflexao("x"));
            } else if (rb_refY.isSelected()) {
                modelList.addElement("- Reflexão em Y");
                listaDeTransformacoes.push(trans2D.geraMatrizReflexao("y"));
            } else if (rb_refXY.isSelected()) {
                modelList.addElement("- Reflexão em XY");
                listaDeTransformacoes.push(trans2D.geraMatrizReflexao("xy"));
            }
        } else if (rb_cisalhamento.isSelected()) {
            modelList.addElement("- Cisalhamento: Cx=" + valorDDX.getValue() + ", Cy=" + valorDDY.getValue());
            listaDeTransformacoes.push(trans2D.geraMatrizCisalhamento((double) valorDDX.getValue(), (double) valorDDY.getValue()));
        }
    }//GEN-LAST:event_btn_addListaActionPerformed

    private void btn_applyTransfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyTransfCActionPerformed
        if (!listaDeTransformacoes.isEmpty()) {
            setTipoAlgoritimo(TransformEnum.COMPOSTA);
            JanelaPrincipal.runResult(this);
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "Você não adicionou nenhum tipo de transformação na lista.\nPor favor, adicione e tente novamente...", "Aplicar Transformações Compostas?", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_applyTransfCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addLista;
    private javax.swing.JButton btn_applyTransf;
    private javax.swing.JButton btn_applyTransfC;
    private javax.swing.JButton btn_desenhar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_dd1;
    private javax.swing.JLabel lab_dd2;
    private javax.swing.JPanel pan_dados1;
    private javax.swing.JPanel pan_dados2;
    private javax.swing.JRadioButton rb_cisalhamento;
    private javax.swing.JRadioButton rb_escala;
    private javax.swing.JRadioButton rb_refX;
    private javax.swing.JRadioButton rb_refXY;
    private javax.swing.JRadioButton rb_refY;
    private javax.swing.JRadioButton rb_reflexao;
    private javax.swing.JRadioButton rb_rotacao;
    private javax.swing.JRadioButton rb_translacao;
    private javax.swing.JSpinner sp_height;
    private javax.swing.JSpinner sp_pointX;
    private javax.swing.JSpinner sp_pointY;
    private javax.swing.JSpinner sp_width;
    private javax.swing.JSpinner valorDDX;
    private javax.swing.JSpinner valorDDY;
    // End of variables declaration//GEN-END:variables
    
    public Ponto getPonto() {
        return ponto;
    }

    public void setPonto(Ponto ponto) {
        this.ponto = ponto;
    }

    public double getValorX() {
        return valorX;
    }

    public void setValorX(double valorX) {
        this.valorX = valorX;
    }

    public double getValorY() {
        return valorY;
    }

    public void setValorY(double valorY) {
        this.valorY = valorY;
    }

    public double getAngulo() {
        return angulo;
    }

    public void setAngulo(double raio) {
        this.angulo = raio;
    }

    public Rectangle2D.Double getRect() {
        return rect;
    }

    public void setRect(Rectangle2D.Double rect) {
        this.rect = rect;
    }

    public String getEixo() {
        return eixo;
    }

    public void setEixo(String eixo) {
        this.eixo = eixo;
    }
    
    public TransformEnum getTipoAlgoritimo() {
        return tipoAlgoritimo;
    }

    public void setTipoAlgoritimo(TransformEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }
    
    private void desenharObjeto() {

        double width = (double) sp_width.getValue();
        double height = (double) sp_height.getValue();

        /**
         * Pegando as coordenadas iniciais do objeto
         */
        double px = (double) sp_pointX.getValue();
        double py = (double) sp_pointY.getValue();

        if (width > 0 && height > 0) {

            matrizObject = new double[3][4];

            // PONTO A
            matrizObject[0][0] = px;
            matrizObject[1][0] = py;
            matrizObject[2][0] = 1;

            // PONTO B
            matrizObject[0][1] = width + px;
            matrizObject[1][1] = 0 + py;
            matrizObject[2][1] = 1;

            // PONTO C
            matrizObject[0][2] = width + px;
            matrizObject[1][2] = height + py;
            matrizObject[2][2] = 1;

            // PONTO D
            matrizObject[0][3] = 0 + px;
            matrizObject[1][3] = height + py;
            matrizObject[2][3] = 1;

            PlanoCartesiano.getInstance().drawObjeto2D(matrizObject);
        } else {
            JOptionPane.showMessageDialog(this.getRootPane(), "Faltou você definir a largura (W) e altura (H) do objeto!", "Desenhar Objeto?", JOptionPane.WARNING_MESSAGE);
        }
    }
    
}
